language: ruby

branches:
  only:
    - master
    - develop

script: bundle exec rake test

rvm:
  - 2.6.2

before_script:
  - bundle exec rake db:migrate RAILS_ENV=test

notifications:
  email:
    on_success: always

addons:
  sauce_connect: true
  code_climate:
    repo_token:
      secure: IUL4myAsn0wg5vp5duw2yrdepgozkHSRR0fmQ709/VLas1tKuIfHKvvmVlLYtpB+cUyunY4ujCjDNxfhwflkjtWUvFWIVGiMwC5amReslR18eiPX75MNfD3msIVaU9hPPzbelxfIDc7xdsYkjBNNm5OmweJkbxrnHQgWOM5MEmM=

env:
  global:
    - secure: Dr7jLhkgYEeHUMQN9m9nsM02yskYZxervGHZAQbBSMvTQ3PUOJoHct7NeHhM8OC+2dR+cLwOFMmxoBiw3pBUCylrzK9oKP+6S5IeoRtyG+YRQNYe4CunAPxVpgon02xaYQTq1SIoZi8WB+1+wN8DRl/Qq/4czRoM44nnrN+dCYE=
    - secure: LFQ8H7e5hBgIKbnZkbW6wRkc6pJ/88H71dXmfTisgA80nrhj+TMkIfMDXvrn/pSQ38LPfkBKltCc+IYV2c2sRumrlhup29g7tLYU/KYVyw/roU8qOoAQu4NjutWzuD01IWS9bO+RScP1P5QLNYDlxUYk5OC4iDZQeo5Jk+RQB3M=
  matrix:
    # Linux tests
    - PLATFORM="Linux" BROWSER="firefox" BROWSER_VERSION="latest"
    - PLATFORM="Linux" BROWSER="chrome" BROWSER_VERSION="latest"

    # Mac OS X tests
    - PLATFORM="macOS 10.13" BROWSER="firefox" BROWSER_VERSION="64" # 65 can't reach site
    - PLATFORM="macOS 10.13" BROWSER="chrome" BROWSER_VERSION="70" # 71 can't reach site
    # - PLATFORM="macOS 10.13" BROWSER="safari" # safari never reaches site
    - PLATFORM="macOS 10.14" BROWSER="firefox" BROWSER_VERSION="64" # 65 can't reach site
    - PLATFORM="macOS 10.14" BROWSER="chrome" BROWSER_VERSION="70" # 71 can't reach site
    # - PLATFORM="macOS 10.14" BROWSER="safari" # safari never reaches site

    # Windows tests
    - PLATFORM="Windows 10" BROWSER="firefox" BROWSER_VERSION="64" # 65 can't reach site
    - PLATFORM="Windows 10" BROWSER="chrome" BROWSER_VERSION="70" # 71 can't reach site
    # - PLATFORM="Windows 10" BROWSER="edge" # edge never reaches site

    # Android tests
    #- PLATFORM="Linux" BROWSER="android" DEVICE_NAME="Android Emulator" DEVICE_ORIENTATION="portrait"
    #- PLATFORM="Linux" BROWSER="android" DEVICE_NAME="Google Nexus 7 HD Emulator" DEVICE_ORIENTATION="portrait"

    # iOS tests
    #- PLATFORM="OS X 10.10" BROWSER="iphone" DEVICE_NAME="iPhone Simulator" DEVICE_ORIENTATION="portrait"
    #- PLATFORM="OS X 10.10" BROWSER="iphone" DEVICE_NAME="iPad Simulator" DEVICE_ORIENTATION="portrait"
