language: ruby
branches:
  only:
    - master
    - develop
script: bundle exec rake test
rvm:
- 1.9.3
- 2.1.5
before_script:
- bundle exec rake db:migrate RAILS_ENV=test
addons:
  sauce_connect: true
  code_climate:
    repo_token:
      secure: IUL4myAsn0wg5vp5duw2yrdepgozkHSRR0fmQ709/VLas1tKuIfHKvvmVlLYtpB+cUyunY4ujCjDNxfhwflkjtWUvFWIVGiMwC5amReslR18eiPX75MNfD3msIVaU9hPPzbelxfIDc7xdsYkjBNNm5OmweJkbxrnHQgWOM5MEmM=
env:
  global:
    - secure: Dr7jLhkgYEeHUMQN9m9nsM02yskYZxervGHZAQbBSMvTQ3PUOJoHct7NeHhM8OC+2dR+cLwOFMmxoBiw3pBUCylrzK9oKP+6S5IeoRtyG+YRQNYe4CunAPxVpgon02xaYQTq1SIoZi8WB+1+wN8DRl/Qq/4czRoM44nnrN+dCYE=
    - secure: LFQ8H7e5hBgIKbnZkbW6wRkc6pJ/88H71dXmfTisgA80nrhj+TMkIfMDXvrn/pSQ38LPfkBKltCc+IYV2c2sRumrlhup29g7tLYU/KYVyw/roU8qOoAQu4NjutWzuD01IWS9bO+RScP1P5QLNYDlxUYk5OC4iDZQeo5Jk+RQB3M=
  matrix:
    # Linux tests
    - PLATFORM="Linux" BROWSER="firefox"
    - PLATFORM="Linux" BROWSER="chrome"

    # Mac OS X tests
    #- PLATFORM="OS X 10.10" BROWSER="safari"
    - PLATFORM="OS X 10.10" BROWSER="firefox"
    - PLATFORM="OS X 10.10" BROWSER="chrome"

    # Windows tests
    #- PLATFORM="Windows 7" BROWSER="internet_explorer"
    - PLATFORM="Windows 7" BROWSER="firefox"
    - PLATFORM="Windows 7" BROWSER="chrome"
    #- PLATFORM="Windows 8.1" BROWSER="internet_explorer"
    - PLATFORM="Windows 8.1" BROWSER="firefox"
    - PLATFORM="Windows 8.1" BROWSER="chrome"

    # Android tests
    #- PLATFORM="Linux" BROWSER="android" DEVICE_NAME="Android Emulator" DEVICE_ORIENTATION="portrait"
    #- PLATFORM="Linux" BROWSER="android" DEVICE_NAME="Google Nexus 7 HD Emulator" DEVICE_ORIENTATION="portrait"

    # iOS tests
    #- PLATFORM="OS X 10.10" BROWSER="iphone" DEVICE_NAME="iPhone Simulator" DEVICE_ORIENTATION="portrait"
    #- PLATFORM="OS X 10.10" BROWSER="iphone" DEVICE_NAME="iPad Simulator" DEVICE_ORIENTATION="portrait"
